version: "3"
services: 
    client:
        build: ./client
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        links:
            - api
        networks:
            - shopifychallenge-network
    
    api:
        build: ./api
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./api:/api
            - /api/node_modules
        networks: 
            - shopifychallenge-network

networks: 
    shopifychallenge-network:
        driver: bridge